/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Empregador: typeof import('./src/components/empregador/Empregador.vue')['default']
    FreeCourses: typeof import('./src/components/free-courses/FreeCourses.vue')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    LoginFormInput: typeof import('./src/components/user/login_form/LoginFormInput.vue')['default']
    MainFrame: typeof import('./src/components/main-frame/MainFrame.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Opportunities: typeof import('./src/components/opportunities/Opportunities.vue')['default']
    OpportunityCard: typeof import('./src/components/empregador/OpportunityCard.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
