/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOpportunityForm: typeof import('./src/components/empregador/AddOpportunityForm.vue')['default']
    BenefitsCheckbox: typeof import('./src/components/empregador/addOpportunityInputs/BenefitsCheckbox.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./src/components/opportunities/opportunities_card/Card.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Empregador: typeof import('./src/components/empregador/Empregador.vue')['default']
    FreeCourses: typeof import('./src/components/free-courses/FreeCourses.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    LoginFormInput: typeof import('./src/components/user/login_form/LoginFormInput.vue')['default']
    MainFrame: typeof import('./src/components/main-frame/MainFrame.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Opportunities: typeof import('./src/components/opportunities/Opportunities.vue')['default']
    OpportunityCard: typeof import('./src/components/empregador/OpportunityCard.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RequirementsList: typeof import('./src/components/empregador/addOpportunityInputs/RequirementsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SimpleInputText: typeof import('./src/components/empregador/addOpportunityInputs/SimpleInputText.vue')['default']
    SimpleInputTextWithIcon: typeof import('./src/components/empregador/addOpportunityInputs/SimpleInputTextWithIcon.vue')['default']
    SimpleSelect: typeof import('./src/components/empregador/addOpportunityInputs/SimpleSelect.vue')['default']
  }
}
